# Generated by Django 2.0.6 on 2018-06-19 07:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 6, 19, 7, 55, 20, 157735, tzinfo=utc))),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
                ('userlevel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlevel', to='recruiter.UserLevel')),
            ],
        ),
    ]
