# Generated by Django 2.0.6 on 2018-06-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20180619_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyvertical',
            options={'ordering': ('name',)},
        ),
    ]
